### PR TITLE
Dead code cleanup

### PR DESCRIPTION
**Pull request by tv42**
No outward behavior change.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Removing range queries?

**Comment by jbenet** [comment]
In the long run we're going to need range queries -- things like resuming operations, listing portions of all local blocks (range queries for the end user / webui) etc. example:



That is currently just dumping all of them out. it will have to be a paginated (or infinity scroll but paginated querying) thing.

**Comment by tv42** [comment]
I'll happily add them back later with a better API. This thing is just wrong ;) Offset+limit is the wrong tool for querying mutating data, and channels are not python generators.

**Comment by jbenet** [comment]
kk sounds good.

**Pull request merged**
