### PR TITLE
sharness test: ipfs add -r

### PR DESCRIPTION
**Pull request by jbenet**
Taking over from https://github.com/jbenet/go-ipfs/pull/393

### CODE REVIEW

**Comment by jbenet** [comment]
Interesting... on osx it passes with my hash change. But travis and jenkins opine differently:

```
-added QmWSgS32xQEcXMeqd3YPJLrNBLSdsfYCep2U7CFkyrjXwY mountdir/planets
+added QmPikaYYDyDNeZ4uGpDZJuA3EUgmq9ubhNHkXWWUrcwFz6 mountdir/planets
 added QmPrrHqJzto9m7SyiRzarwkqPcCSsKR2EB1AyqJfe8L8tN mountdir/planets/mars.txt
 added QmU5kp3BH3B8tnWUU2Pikdb2maksBNkb92FHRr56hyghh4 mountdir/planets/venus.txt

not ok 20 - 'ipfs add -r' output looks good
#	
#		PLANETS="QmWSgS32xQEcXMeqd3YPJLrNBLSdsfYCep2U7CFkyrjXwY" &&
#		MARS="QmPrrHqJzto9m7SyiRzarwkqPcCSsKR2EB1AyqJfe8L8tN" &&
#		VENUS="QmU5kp3BH3B8tnWUU2Pikdb2maksBNkb92FHRr56hyghh4" &&
#		echo "added $PLANETS mountdir/planets" >expected &&
#		echo "added $MARS mountdir/planets/mars.txt" >>expected &&
#		echo "added $VENUS mountdir/planets/venus.txt" >>expected &&
#		test_cmp expected actual
```

It looks like the directory hash is being calculated differently on osx and linux!! I've never encountered this before. cc @whyrusleeping @chriscool

**Comment by jbenet** [comment]
confirmed in another linux machine:
```
not ok 20 - 'ipfs add -r' output looks good
#
#		PLANETS="QmWSgS32xQEcXMeqd3YPJLrNBLSdsfYCep2U7CFkyrjXwY" &&
#		MARS="QmPrrHqJzto9m7SyiRzarwkqPcCSsKR2EB1AyqJfe8L8tN" &&
#		VENUS="QmU5kp3BH3B8tnWUU2Pikdb2maksBNkb92FHRr56hyghh4" &&
#		echo "added $PLANETS mountdir/planets" >expected &&
#		echo "added $MARS mountdir/planets/mars.txt" >>expected &&
#		echo "added $VENUS mountdir/planets/venus.txt" >>expected &&
#		test_cmp expected actual
#
```

**Comment by jbenet** [comment]
by the way @chriscool -- we wont be able to keep the sorted output on add if we want to do streaming output before all files are added (it isn't now, but will be). maybe an `ipfs add --sorted -r <dir>` option is in order

**Comment by whyrusleeping** [comment]
@jbenet I think we need to ship our own little hash tool, as its not reliably installed on every system. Maybe a simple little go program that reads in from stdin and outputs a sha256 hash to stdout.

**Comment by jbenet** [comment]
i wanted this yesterday. sec, @whyrusleeping on it.

**Comment by jbenet** [comment]
@whyrusleeping:

```
go get github.com/jbenet/go-multihash/multihash
```

maybe we can move to using this ;)

**Comment by jbenet** [comment]
rebased this on master. dont think the tests will pass yet-- (hashing issue)

**Comment by jbenet** [comment]
oh, @whyrusleeping 
> @jbenet I think we need to ship our own little hash tool, as its not reliably installed on every system. 

did you mean this is why the hashes fail? no, _ipfs_ is returning different hashes for the same file! (this is unixfs)

**Comment by jbenet** [comment]
Yep. looks like that (keeping links sorted by name) was it!

**Comment by jbenet** [comment]
Rebased, putting my commit first, so all tests should pass.

**Comment by whyrusleeping** [comment]
In regards to the hash tool, I just wanted that because shasum isn't always installed on every machine, but our tests rely on it

**Comment by jbenet** [comment]
@chriscool thanks again for this test! :smile:  might be good to add a bigger one (testing maybe a generated deep directory hierarchy. we only need to check the last hash, too)

**Comment by chriscool** [comment]
@jbenet thanks for fixing this! :-)
By the way you said yesterday above that sorting the output (commit d490a85) was bad if we want to stream the output, but you merged the commit that does it. Is it a mistake or should we add the --sorted option to fix that?

**Comment by chriscool** [comment]
And ok I will think about adding a bigger test.

**Comment by jbenet** [comment]
> Is it a mistake or should we add the --sorted option to fix that?

Ah, good catch. @mappum's last PR makes it stream. I'll revert the commit.

**Comment by jbenet** [comment]
@chriscool fixed in 0395a7a

**Pull request merged**
