### PR TITLE
refactor core package and add 'net generator' interface

### PR DESCRIPTION
**Pull request by whyrusleeping**
Im working on refactoring core a little bit. All ive done so far is to break it into separate files. My goal is to be able to pass in my own network object (see the NetworkGenerator interface) so i can make dhthell run easily on a mocknet OR a real net. @briantigerchow Feel free to push to this branch any changes you like, since i trust your intuition on interfaces far more than my own.

Oh yeah, WIP

### CODE REVIEW

**Comment by briantigerchow** [comment]
rebase on #454. core interface changes to accept routing option there.

**Comment by whyrusleeping** [comment]
Cool, will do!

**Comment by briantigerchow** [comment]
Breaking the file apart into separate elements has the effect of concretizing the existing structure. I've been mulling over the design for well over a month at this point and still believe that a good structure hasn't yet emerged. I'd be hesitant to let the concrete before the complexity of construction has been reigned in.

By all means, feel free to explore. I would however, advise that you delay breaking things apart until you're satisfied with the quality.

**Comment by whyrusleeping** [comment]
yeah, i can see that. My main motivation for breaking the files out is to make it easier to work with, i really dislike 500+ line files...

**Comment by briantigerchow** [comment]
With that said, this change can be accommodated without significant structural modifications.

This type signature will give you everything you need:

```Go
func Foo(pri ic.PrivKey, pid peer.ID) core.HostOption {
  return func(context.Context, *core.IPFSNode) (host.Host, error) {
  }
}
```

see: https://github.com/jbenet/go-ipfs/blob/feat/grandcentral-routing/core/corerouting/core.go

**Comment by whyrusleeping** [comment]
Thats pretty much the pattern im using for this, (although HostOption is probably a better name than the one i chose)

**Comment by whyrusleeping** [comment]
I think the only thing missing from it being really easy to set up a core.IpfsNode is an easy way to construct a Repo. the repo.Mock object just needs quickie constructor function

**Comment by whyrusleeping** [comment]
Closing until further thought is had

**Comment by briantigerchow** [comment]
Yeah. Came back to mention that passing identity variables into the host option closure won't work because it's in the repo. I see you've already discovered this. Starting to think that you'll get what you want by having a niladic Foo and using a repo constructor as you mentioned.

**Pull request closed without merging**
