### PR TITLE
test/sharness: improve t0111 using test_cmp

### PR DESCRIPTION
**Pull request by chriscool**
License: MIT
Signed-off-by: Christian Couder <chriscool@tuxfamily.org>

### CODE REVIEW

**Comment by chriscool** [comment]
Same build errors as for #717 (test/sharness: improve t0090 by using printf).

**Comment by jbenet** [comment]
Same story as https://github.com/jbenet/go-ipfs/pull/717#issuecomment-72404989 -- rebased on new master. previous ref was: 20426e5

**Comment by jbenet** [comment]
once more on top of 1d9d13e (sorry for the rebases @chriscool -- am trying to cleanup the testing bug mess. need to get hyper reliable testing)

**Comment by jbenet** [comment]
(this might still fail with the odd bug we have in some test machines. if so i'll merge it anyway since that's unrelated)

**Pull request merged**
