### PR TITLE
Repo cleanup

### PR DESCRIPTION
**Pull request by tv42**
This simplifies fsrepo to prepare for future changes. The should be no change in behavior.

Redo of https://github.com/jbenet/go-ipfs/pull/916 to wake up jenkins.

### CODE REVIEW

**Comment by jbenet** [comment]
this passed. `TestBootstrap` is one of our known timing tests :/ https://github.com/jbenet/go-ipfs/issues/188#issuecomment-78059013

**Comment by jbenet** [comment]
@tv42 to confirm before i merge-- this doesnt change the repo layout at all, right? no migration needed?

**Comment by tv42** [comment]
@jbenet Any change is behavior would be a bug.

**Comment by jbenet** [comment]
Great! let's ship it

**Pull request merged**
