### PR TITLE
dont send ip6 link local addrs

### PR DESCRIPTION
**Pull request by jbenet**

### CODE REVIEW

**Comment by jbenet** [comment]
@whyrusleeping or @briantigerchow look this over just to make sure i didnt screw up, but should be solid.

**Comment by jbenet** [comment]
This will fix #529

**Comment by briantigerchow** [comment]
LGTM

**Comment by jbenet** [comment]
@briantigerchow couple commits more ^ and: 

- https://build.protocol-dev.com/job/all-the-tests/529/ --any idea why this one failed?
- https://build.protocol-dev.com/job/network-test/724/console -- cassiopeia docker not running cc @whyrusleeping

**Comment by jbenet** [comment]
@whyrusleeping please remove cassiopeia from jenkins when you work on it. it's failing the tests :(

**Comment by whyrusleeping** [comment]
LGTM, sorry about the failures... didnt think it would still try to run while down

**Comment by jbenet** [comment]
Despite what jenkins is confused about-- the tests passed. I'm merging this

**Comment by Mikaela** [comment]
I am wondering why IPv6 link-local addresses don't have a listener on them in ipfs log messages and found here. Are the addresses used in reality or does IPFS explicitly not use them?

What if there are multiple IPFS nodes in the same network, will they detect each other automatically and shouldn't they be using IPv6? I don't think announcing LAN IPv4 addresses is a solution, because I have disabled announcing all IPv4 addresses, because I am always behind CGN anyway and there is no way around it other than using IPv6 (or Yggdrasil or Cjdns or https://github.com/ipfs/go-ipfs/issues/4110(?)).

*Sorry if I am not making much sense, I am not a native speaker and it's 01:18 and I should be sleeping.*

**Comment by Stebalien** [comment]
We explicitly do not use them. Unfortunately, there are a bunch of tricky issues around supporting link-local addresses:

1. They're relative (due to the zone). We'd only be able to use them with, e.g., mdns and we'd have to carefully record the link on which we received such advertisements. Much of our code assumes that all multiaddrs are "absolute" (work the same everywhere) so we'd have to put some effort into fixing this.
2. We only recently added support for the zones in multiaddr and we haven't added support to the rest of libp2p. We're not even sure if we're happy with how we added zone support.

**Pull request merged**
