### PR TITLE
linkblock size calc test

### PR DESCRIPTION
**Pull request by jbenet**
this PR sets the linkblock size to 8KB based on
calculations of total data addressable

### CODE REVIEW

**Comment by jbenet** [comment]
@whyrusleeping help appreciated on this error

**Comment by whyrusleeping** [comment]
Ill take a look at it.

**Comment by whyrusleeping** [comment]
Oh yeah... the indirect block changes break the DAGModifier, which is why i wanted to make ipns readonly until after alpha (when we have more time to refactor that area of the codebase)

**Comment by jbenet** [comment]
So where does that put us? how do i fix this?

**Comment by whyrusleeping** [comment]
We should probably disable the ipns tests, and put a warning message on mounting ipns

**Comment by jbenet** [comment]
If this breaks ipns, we should then disable ipns entirely. we should not have known _broken_ things-- it makes the whole tool feel unreliable

**Comment by whyrusleeping** [comment]
Well, it only breaks ipns writing. The reading part of it is fine. We can simply make ipns readonly

**Comment by jbenet** [comment]
@whyrusleeping okay -- wanna push that onto this branch?

**Pull request merged**
