### PR TITLE
New Binary: Gateway Fileserver

### PR DESCRIPTION
**Pull request by briantigerchow**
after #642 

This doesn't necessarily need to be in this repository, but users may find these examples of IPFS used as a library instructive.

### CODE REVIEW

**Comment by briantigerchow** [comment]
RFCR @jbenet @whyrusleeping @mappum 

This node should probably reprovide keys occasionally huh?

(refreshing the assets should do it, but perhaps we want to be explicit?)

**Comment by briantigerchow** [comment]
@jbenet 

```
cd cmd/ipfs-gateway-fs
go run main.go --assets-path . --refresh-assets-interval 1s
2015/01/24 02:17:47 refreshed asset README.md   (key: QmTDNgLR3UGi8KbDppDscCqmd12PtoZtrrqge6x5Gi6md6)

open http://localhost:8080/ipfs/QmTDNgLR3UGi8KbDppDscCqmd12PtoZtrrqge6x5Gi6md6
```

**Comment by jbenet** [comment]
@briantigerchow i meant test it as in with a sharness test:

```sh
test_expect_success "'ipfs-gateway-fs' succeeds" '
	ipfs-gateway-fs --address :8080 --assets-path . --refresh-assets-interval 1s & &&
	GFSPID=$!
'

test_expect_success "'ipfs-gateway-fs' is still running" '
  kill -0 $GFSPID
'

test_expect_success "'ipfs-gateway-fs' auto-imports changes" '
	echo "hello world" > expected && 
	HASH=`<expected hash>` && 
	sleep 2 &&
	curl "http://127.0.0.1:8080/ipfs/$HASH"  > actual &&
	test_cmp expected actual
'

test_expect_success "'ipfs-gateway-fs' is still running" '
  kill -0 $GFSPID
'

test_expect_success "'ipfs-gateway-fs' can be killed" '
  test_kill_repeat_10_sec $GFSPID
'
```

**Pull request merged**
