### PR TITLE
races: fix race conditions

### PR DESCRIPTION
**Pull request by jbenet**

### CODE REVIEW

**Comment by jbenet** [comment]
related to #569

**Comment by briantigerchow** [comment]
Lgtm. Once merged let's enable the race detector on CI.

**Comment by whyrusleeping** [comment]
LGTM

**Comment by jbenet** [comment]
@briantigerchow what do we need to do for
> let's enable the race detector on CI
?

**Comment by briantigerchow** [comment]
pasted_image_1_20_15__5_05_pm

**Pull request merged**
