### PR TITLE
Allow FSRepo components to depend on the config, add log config to eventlog

### PR DESCRIPTION
**Pull request by briantigerchow**
@whyrusleeping @jbenet

### CODE REVIEW

**Comment by briantigerchow** [comment]
@whyrusleeping you can now control max log size using the `Log.MaxSizeMB` variable 

image

**Comment by jbenet** [comment]
:clap: :clap: what should it default to? something like: 

```
MaxSizeMB: 500,
```
?

**Comment by whyrusleeping** [comment]
:+1:

**Comment by jbenet** [comment]
The logs are still growing unboundedly in all the machines. :/

**Comment by briantigerchow** [comment]
Did you set the config value and reboot the processes?

**Comment by briantigerchow** [comment]
realized that it's also necessary to set MaxBackups. The default value of 0 allows an unlimited number of backups. Turns out MaxSizeMB is the threshold for rolling over, not a cap.

**Pull request merged**
