### PR TITLE
Fix a mild race condition in `mount_darwin.go`

### PR DESCRIPTION
**Pull request by kkoroviev**
Found in the process of fixing #945.

It doesn't solve #945, but it solves the race conditions that I've mentioned there.

### CODE REVIEW

**Comment by kkoroviev** [comment]
@jbenet

It's better not to merge this, but modify the upstream.

**Comment by kkoroviev** [comment]
CC @tv42.

**Comment by tv42** [comment]
Good catch, working on it.

**Comment by jbenet** [comment]
yay open source at work \o/ -- gj @kkoroviev

**Comment by tv42** [comment]
Through the power of Git, I just literally cherry-picked that commit and all the paths and everything just worked right!

Fixed in https://github.com/bazillion/fuse/commit/79d103f5608724e3ccee0a10daccc5e4aff03591

**Comment by cryptix** [comment]
Closing in favor of #958.

**Pull request closed without merging**
