### PR TITLE
Use multihash not shasum

### PR DESCRIPTION
**Pull request by chriscool**

### CODE REVIEW

**Comment by chriscool** [comment]
@jbenet There is this error on Travis:

```
expecting success:
IPFS_PID=$! &&
test_wait_output_n_lines_60_sec actual_daemon 2 &&
test_run_repeat_60_sec "grep \"API server listening on $ADDR_API\" actual_daemon" ||
test_fsh cat actual_daemon || test_fsh cat daemon_err
> cat actual_daemon
Initializing daemon...
Gateway server listening on /ip4/127.0.0.1/tcp/8080
> cat daemon_err
not ok 4 - 'ipfs daemon' is ready
```

It looks like we are expecting "API server..." and we get "Gateway server..."
Maybe a problem in f1d34a2a?

**Comment by jbenet** [comment]
> It looks like we are expecting "API server..." and we get "Gateway server..."

It's supposed to have both. The test is right to fail, as the API hasn't come up in >60s-- but there's a bad failure going on: maybe binding to the port fails, and it fails silently? (it's really annoying as happens all the time, and not clear to me what's going on)

**Comment by chriscool** [comment]
Ok. If there are other important steps between the Gateway coming up and the API coming up, maybe other messages could be printed and checked in the tests. That could narrow down which code is failing.

Or could it be a network failure, and are there ways to monitor those on Travis?

Anyway it is not related to the changes in this PR.

**Comment by jbenet** [comment]
> Or could it be a network failure, and are there ways to monitor those on Travis?

I think it is-- there's nothing important between the gateway and API. the likely explanation is a port clash. I think it may be best to move towards making the API able to start on an unspecified (kernel assigned) port. (this is non trivial at the moment).

> Anyway it is not related to the changes in this PR.

LGTM, thanks!

**Pull request merged**
