### PR TITLE
feat(core) replace config.Config with repo.Repo

### LINKED ISSUE #376: introduce "repo" package to manage IPFS_DIR concerns
**issue**

Introducing `daemon --init` broke `eventlog` configuration. Here's why:

1) Now, users may run `daemon` without an initialized repo.
2) the `configureLogger` hook checks to see whether the command `usesConfig` and `usesRepo`. If both are true, the logger is configured to use the IPFS_DIR. This is necessary since the logger logs to a file.

Since the daemon doesn't require a repo/config and configureLogger only runs if the upcoming command uses the config/repo, logs are not configured before running the daemon.

Notice that the one actual requirement for the hook is the existence of a config/repo.

Therefore, we should just check this property directly.

-- 

**proposal**

I propose we introduce a `repo` package to handle IPFS_DIR concerns. This would include the concern described in #358 (locking the repo).

Initially the package would have these exported functions:

- [ ] func IsInitialized bool
- [ ] func IsLocked bool
- [ ] func Lock *Lock

--

Also...

We've also discussed centralizing option precedence. ie. the logic that determines whether to use environment variables, user-provided CLI arguments, or config file values to determine the value of an option (eg. debug). This may be out of the scope of this issue.

### PR DESCRIPTION
**Pull request by briantigerchow**
closes #376 RFCR @jbenet

### CODE REVIEW

**Comment by jbenet** [comment]
LGTM but see failing tests

**Comment by briantigerchow** [comment]
failing test is 

ok  	github.com/jbenet/go-ipfs/util	0.228s
--- FAIL: TestDeadlineFractionHalf (0.01 seconds)
	fracctx_test.go:75: ctx1 ended too early

**Comment by jbenet** [comment]
> TestDeadlineFractionHalf -- `if jenkins.Skip()`

Yeah, sure. sigh timing.

@briantigerchow and https://build.protocol-dev.com/job/network-test/930/console

**Comment by briantigerchow** [comment]
> @briantigerchow and https://build.protocol-dev.com/job/network-test/930/console

Ah thanks. Missed that. Thank goodness for online tests.

**Comment by briantigerchow** [comment]
All tests pass, but I'd like to read through one more time before merging. Mind if I merge this tomorrow?

**Comment by jbenet** [comment]
@briantigerchow :+1: no rush

**Comment by briantigerchow** [comment]
this is tested pretty thoroughly, but it's changes are cross-cutting so I still worry about regressions. Going to merge now. Let me know if you experience any strange issues around `core.IpfsNode` Close().

@whyrusleeping @jbenet

**Pull request merged**
