### PR TITLE
multiaddrs with .../ipfs/...

### PR DESCRIPTION
**Pull request by jbenet**
This commit adds multiaddr support for "proper ipfs addresses", and
tries it out in bootstrap peers.

:warning: this commit makes your current configs unusable, as the default
bootstrap peers. You may need to edit your config.

Go from:

```js
Bootstrap: [
  {
    "Address": "/ip4/104.131.131.82/tcp/4001",
    "PeerID": "QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"
  }
]
```

To:

```js
Bootstrap: [
  "/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"
]
```
Note the `.../ipfs/...`

### CODE REVIEW

**Comment by jbenet** [comment]
This builds on #583

**Comment by jbenet** [comment]
The relevant part is only  fd041ec...4f2c313 -- will be clearer once #583 merges.

**Comment by whyrusleeping** [comment]
Interesting that the network test failed... not entirely sure why that would happen. "files didnt match"

**Comment by jbenet** [comment]
i think it's the reuse port-- sec

**Comment by jbenet** [comment]
ah no-- it was a test case fix.

**Comment by jbenet** [comment]
```
Error: failed to parse ip4:  failed to parse ip4 addr: 
```
It may be some config / bootstrap addr problem.

**Comment by briantigerchow** [comment]
The network test has manually-defined bootstrap configs.

**Comment by jbenet** [comment]
RFCR here @whyrusleeping or @briantigerchow 

And, @briantigerchow not sure what's going wrong with the network test. this error is different than before. any ideas? looks like it broke fig:

```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/code/build/fig/out00-PYZ.pyz/threading", line 552, in __bootstrap_inner
  File "/code/build/fig/out00-PYZ.pyz/threading", line 505, in run
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.multiplexer", line 41, in _enqueue_output
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.log_printer", line 59, in _make_log_generator
  File "/code/build/fig/out00-PYZ.pyz/fig.container", line 141, in wait
  File "/code/build/fig/out00-PYZ.pyz/docker.client", line 940, in wait
  File "/code/build/fig/out00-PYZ.pyz/docker.client", line 73, in _post
  File "/code/build/fig/out00-PYZ.pyz/requests.sessions", line 425, in post
  File "/code/build/fig/out00-PYZ.pyz/requests.sessions", line 383, in request
  File "/code/build/fig/out00-PYZ.pyz/requests.sessions", line 486, in send
  File "/code/build/fig/out00-PYZ.pyz/requests.adapters", line 374, in send
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
```

**Comment by mappum** [comment]
Looks like these changes breaks `ipfs bootstrap`. I'm not sure if it affects `ipfs swarm` since it's not connecting me to anyone.

**Comment by briantigerchow** [comment]
@jbenet 

re: network test error.

On first glance, that looks like an actual bug/error.

**Comment by jbenet** [comment]
@mappum 
> Looks like these changes break ipfs bootstrap. I'm not sure if it affects ipfs swarm since it's not connecting me to anyone.

It changes the config format. can you try removing the bootstrap entry from config and retrying? Actually, can you test whether:

```
ipfs bootstram rm --all
```

works? maybe try an
```
ipfs config 
```
version. (need to find out exactly what we can tell users)

**Comment by mappum** [comment]
Those errors happened after I already `ipfs init`'d on this branch.

**Comment by mappum** [comment]
The error happens for all commands if there is a config file with the old bootstrap format. I deleted my `~/.go-ipfs` directory, and `ipfs init`'d with this branch, and the error still happens on `ipfs bootstrap` (but only if the daemon is running).

**Comment by whyrusleeping** [comment]
I may have to update some parsing in ipfs ping due to this change.

**Comment by jbenet** [comment]
I've rebased this. I want to get it merged in today.

- @mappum i couldnt get your error. works fine for me? (did you reboot your daemon earlier on?)
- @whyrusleeping what code? want to push it onto this branch?

**Comment by jbenet** [comment]
fixed a bug: 
```diff
index 7ae4fde..b1d1f25 100644
--- a/core/bootstrap.go
+++ b/core/bootstrap.go
@@ -233,7 +233,7 @@ func toPeerInfo(bp config.BootstrapPeer) peer.PeerInfo {
 	// of the codebase currently uses addresses without the peerid part.
 	m := bp.Multiaddr()
 	s := ma.Split(m)
-	m = ma.Join(s[len(s)-1])
+	m = ma.Join(s[:len(s)-1]...)
 
 	return peer.PeerInfo{
 		ID:    bp.ID(),

```

**Comment by whyrusleeping** [comment]
Im getting the same problems as @mappum cant bootstrap to anyone

**Comment by whyrusleeping** [comment]
Pushed my fix for pings address parsing here

**Comment by jbenet** [comment]
@whyrusleeping @mappum saw what you meant.  fixed in 188d336

**Pull request merged**
