### PR TITLE
Implement recursive indirect block creation for DAGs

### PR DESCRIPTION
**Pull request by whyrusleeping**
Also cleaned up a bunch of code related to building and reading DAGs

### CODE REVIEW

**Comment by jbenet** [comment]
rebased this on new master.

**Comment by jbenet** [comment]
Clear problems:
- hangs tests on my machine (osx): `TestBatchFetch`
- hashes for sharness seem to be off: https://build.protocol-dev.com/job/sharnessss/408/console
- not clear all commits will pass tests (use `make test_all_commits`)

**Comment by whyrusleeping** [comment]
Ive fixed the tests hanging. That was a stupid mistake on my part. 

The hashes being off is strange; in the case of the 'welcome to ipfs' object, its making an extra link to a block with just a few bytes. even though the data is smaller than what our block size should be...

And to address not all of the commits passing, i just smashed them all into one nice little package :+1:

**Comment by jbenet** [comment]
> Ive fixed the tests hanging. That was a stupid mistake on my part.

What was it?

> The hashes being off is strange; in the case of the 'welcome to ipfs' object, its making an extra link to a block with just a few bytes. even though the data is smaller than what our block size should be...

Odd.

> And to address not all of the commits passing, i just smashed them all into one nice little package :+1:

Okay. 

Idk where i stand on this... ideally i would like every commit to be as small as possible, to have an atomic progression of improvements. However, in practice, it's painful to rewrite complex (>30 commits) histories. _shrug_

**Comment by whyrusleeping** [comment]
The issue was that for the tests, i was adding the file into an offline mode blockservice, then trying to read it from a network of online blockservices.

**Pull request merged**
