### PR TITLE
install-sharness.sh: use git instead of wget and shasum

### PR DESCRIPTION
**Pull request by chriscool**
This is the first step to address issue #500 (Start using `multihash` tool instead of `shasum`)

License: MIT
Signed-off-by: Christian Couder <chriscool@tuxfamily.org>

### CODE REVIEW

**Comment by chriscool** [comment]
There is this weird error in Travis:

```
? github.com/jbenet/go-ipfs/routing [no test files]
22:28:45.715 ERROR dht: closestPeers query run error: routing: not found prefixlog.go:110
22:28:46.270 ERROR dht: closestPeers query run error: routing: not found prefixlog.go:110
22:28:46.277 ERROR dht: closestPeers query run error: routing: not found prefixlog.go:110
22:28:46.285 ERROR dht: closestPeers query run error: routing: not found prefixlog.go:110
22:28:46.295 ERROR dht: closestPeers query run error: routing: not found prefixlog.go:110
22:28:46.303 ERROR dht: closestPeers query run error: routing: not found prefixlog.go:110
22:28:46.314 ERROR dht: closestPeers query run error: routing: not found prefixlog.go:110
22:28:46.321 ERROR dht: closestPeers query run error: routing: not found prefixlog.go:110
...
```

@jbenet @whyrusleeping do you have an idea about this error?

**Comment by jbenet** [comment]
@chriscool that's our over use of `log.Error`. those are expected "errors" in the test cases-- the real problem is:

```
--- FAIL: TestConnectCollision (1.76 seconds)
	dht_test.go:659: Timeout received!
```

TestConnectCollision is currently a time-based test and it seems travis still runs into problems with those. 

Perhaps the [timeout](https://github.com/chriscool/go-ipfs/blob/sharness_download/routing/dht/dht_test.go#L652) should be longer than a second. (wish we could get rid of timing tests entirely -- hard with the network).

Anyway, not your fault. I'll trigger the test again which will green it-- will increment the timeout in another commit soon.

**Comment by jbenet** [comment]
LGTM!

**Comment by chriscool** [comment]
I have to work on go-multihash now, so there will be a new PR in go-multihash.
When I come back to work on go-ipfs, I can create a new PR, so you can merge this now.

**Comment by jbenet** [comment]
@chriscool okay :+1:

**Pull request merged**
