### PR TITLE
Would like to discuss how Sharness test helpers should be organized

### PR DESCRIPTION
**Pull request by kkoroviev**
Not a real PR.

### CODE REVIEW

**Comment by jbenet** [comment]
This type of thing looks good to me. we should lean to using `sh` / unix tools as much as we can, and lean on this where necessary. There's also the ability to create simple tools like, a "json-selector" tool:

```
> cat whatever.json
{
  "foo": {
    "bar": [ 
      { "name": "Foo Bar" }
    ]
  }
}
> cat whatever.json | json-select foo.bar[0].name
Foo Bar
```

so it can test the structure of things.

(This likely already exists in go, and we could vendor it, just using it as an example)

**Comment by cryptix** [comment]
For the json helper you might want to look at [jq](https://stedolan.github.io/jq/) it's pretty much that on steroids ;)

**Comment by chriscool** [comment]
LGTM too!

**Comment by jbenet** [comment]
is there more discussion here? else lets close it

**Comment by kkoroviev** [comment]
@jbenet

Ahem, yes.

I want `test/sharness/` to have its own `bin/` (`test/sharness/bin/` is symlinked to `../bin/` now).

The `PATH` should contain `test/bin/` and `test/sharness/bin/`, in that order.

Then, I'm not sure how to get sources from `test/sharness/src/` to be compiled into binaries in `test/sharness/bin/`.

**Comment by kkoroviev** [comment]
When the tests pass, we can close this PR without merging.

**Comment by chriscool** [comment]
@kkoroviev are you sure it is valuable for `test/sharness/bin` to not just be a symlink to `../bin`?
Is it a problem if sharness and other tests share their binaries?

**Comment by kkoroviev** [comment]
@chriscool

Anything goes, as long as I can get my "scripts" to run in Sharness tests without rewriting any Makefiles. I mean, rewrite one Makefile now and then don't touch them when I need to add yet another "script".

I am not very good at writing Makefiles, so anyone's help will be much appreciated.

**Comment by jbenet** [comment]
> I want test/sharness/ to have its own bin/ (test/sharness/bin/ is symlinked to ../bin/ now).

Is the purpose here to avoid writing a `Makefile` target? The makefile is used to both 
- make sure all test dependencies are built (may include installing things)
- running the tests

> as long as I can get my "scripts" to run in Sharness tests without rewriting any Makefiles.

new binaries _may_ require modification. It's possible we can setup an abstract target, but in practice it may require some modification. 

> I am not very good at writing Makefiles, so anyone's help will be much appreciated.

`Makefiles` are subtly simple. They feel arcane because of their syntax and some non-obvious choices. I recommend watching: Making Make Make Sense: https://www.youtube.com/watch?v=dsqBSgdQz_8 (can speed it up). It's made by isaacs and runs through lots of tricky bits. `make` is one of those tools that is amazingly simple + useful once you come to firmly grasp its model. Like git.

Moreover, we can help you change these things, by commenting, showing you examples, or answering questions.

**Comment by kkoroviev** [comment]
Thanks, everyone. Closing.

**Pull request closed without merging**
