### PR TITLE
fix the tests

### PR DESCRIPTION
**Pull request by jbenet**
this PR will get our tests back to green

### CODE REVIEW

**Comment by jbenet** [comment]
Looks like fuse broke sometime in the last week. 

```
./t0040-add-and-cat.sh
ok 1 - ipfs init succeeds
ok 2 - prepare config -- mounting and bootstrap rm
ok 3 - 'ipfs daemon' succeeds
ok 4 - 'ipfs daemon' is ready
ok 5 - 'ipfs mount' succeeds
ok 6 - 'ipfs mount' output looks good
ok 7 - 'ipfs add --help' succeeds
ok 8 - 'ipfs add --help' output looks good
ok 9 - 'ipfs cat --help' succeeds
ok 10 - 'ipfs cat --help' output looks good
ok 11 - ipfs add succeeds
ok 12 - ipfs add output looks good
ok 13 - ipfs cat succeeds
ok 14 - ipfs cat output looks good
ok 15 - cat ipfs/stuff succeeds
not ok 16 - cat ipfs/stuff looks good
#
#		test_cmp expected actual
#
ok 17 - 'ipfs add -q' succeeds
ok 18 - 'ipfs add -q' output looks good
ok 19 - 'ipfs add -r' succeeds
ok 20 - 'ipfs add -r' output looks good
ok 21 - go-random is installed
ok 22 - generate 5MB file using go-random
ok 23 - sha1 of the file looks ok
ok 24 - 'ipfs add bigfile' succeeds
ok 25 - 'ipfs add bigfile' output looks good
ok 26 - 'ipfs cat' succeeds
ok 27 - 'ipfs cat' output looks good
ok 28 - cat ipfs/bigfile succeeds
ok 29 - cat ipfs/bigfile looks good
ok 30 # skip generate 100MB file using go-random (missing EXPENSIVE)
ok 31 # skip sha1 of the file looks ok (missing EXPENSIVE)
ok 32 # skip ipfs add bigfile succeeds (missing EXPENSIVE)
ok 33 # skip ipfs add bigfile output looks good (missing EXPENSIVE)
ok 34 # skip ipfs cat succeeds (missing EXPENSIVE)
ok 35 # skip ipfs cat output looks good (missing EXPENSIVE)
ok 36 # skip ipfs cat output hashed looks good (missing EXPENSIVE)
ok 37 # skip cat ipfs/bigfile succeeds (missing EXPENSIVE of FUSE,EXPENSIVE)
ok 38 # skip cat ipfs/bigfile looks good (missing EXPENSIVE of FUSE,EXPENSIVE)
ok 39 - ipfs add -w succeeds
ok 40 - ipfs add -w output looks good
ok 41 - 'ipfs daemon' is still running
ok 42 - 'ipfs daemon' can be killed
# failed 1 among 42 test(s)
1..42
```

Bisecting, it looks like it was introduced in: c88340b5a467fc3efbf98a5e677331b2571977fe

cc @whyrusleeping @cryptix

**Comment by jbenet** [comment]
- [ ] `TestBitswapWithoutRouting` sometimes fails

```
--- FAIL: TestBitswapWithoutRouting (0.00 seconds)
	bitswap_wo_routing_test.go:29: test initialization error
[0;37m14:46:58.193 [35mCRITI [0;34m  boguskey: [0mTestBogusPrivateKey.Sign -- this better be a test! [0;37m<autogenerated>:21[0m
FAIL
FAIL	github.com/jbenet/go-ipfs/test/integration	21.656s
```

- [ ] data race in https://build.protocol-dev.com/job/race/17386/console

**Comment by whyrusleeping** [comment]
@jbenet you should look at pull #838 into this.

**Comment by jbenet** [comment]
@whyrusleeping thanks for ptr. merged #838

**Comment by jbenet** [comment]
The recent failures in:
- https://travis-ci.org/jbenet/go-ipfs/jobs/52756276
- https://travis-ci.org/jbenet/go-ipfs/jobs/52756274

perhaps indicate that the dreadful `'ipfs daemon' is ready` failures _are not_ port related, as previously thought. (not certain, but likely -- the recent changes use a different port for each sharness run, and these ran in their own travis vm, which is unlikely to cause a port clash)

**Comment by jbenet** [comment]
If anyone can get that problem (the dreadful `'ipfs daemon' is ready` failures) solved, it would be awesome. I'm not having much luck figuring out why it's hanging.

Possible that changing the daemon to load the http servers before bootstrapping will make the problem go away. (though the weird thing is this hang happens _after_ bootrstrap, after at least either the http gateway or API line has printed...)

**Comment by jbenet** [comment]
thanks @cryptix -- for fixing the worst

**Pull request merged**
