### PR TITLE
Fix godep restore

### PR DESCRIPTION
**Pull request by chriscool**

### CODE REVIEW

**Comment by chriscool** [comment]
It would be nice to have an automatic test that does "cd test/dependencies && make" to avoid these problems.

**Comment by chriscool** [comment]
The "race" Jenkins test failed with:

```
ok  	github.com/jbenet/go-ipfs/p2p/protocol/relay	23.138s
--- FAIL: TestStBackpressureStreamWrite (11.00 seconds)
	backpressure_test.go:343: continuous should have been faster
FAIL
FAIL	github.com/jbenet/go-ipfs/p2p/test/backpressure	11.029s
```

but it works locally on my machine.

**Comment by jbenet** [comment]
@chriscool 
- apologies for the timing dependent tests failing on CI. we really need to fix this.
- and also sorry, i hadnt pushed https://github.com/jbenet/go-multiaddr/commit/c13f11bbfe6439771f4df7bfb330f686826144e8
- @briantigerchow did you push inflect?
- yes, we should add a test that makes sure all the other repos are accessible.

@chriscool I'm curious, why do you need to godep restore? (so that `make vendor` works?)

**Comment by chriscool** [comment]
@jbenet yeah I want to use a recent version of go-multihash so that we can use the multihash tool instead of shasum. Right now we use jbenet/go-multihash@8ce5cb1 which is old.

**Comment by jbenet** [comment]
I'm also at briantigerchow/inflect@90ecbd7 -- the diff I see with what's in the godep workspace is:

```
> diff -r ../../briantigerchow/inflect Godeps/_workspace/src/github.com/briantigerchow/inflect
Only in ../../briantigerchow/inflect: .git
diff -r ../../briantigerchow/inflect/languages/english.go Godeps/_workspace/src/github.com/briantigerchow/inflect/languages/english.go
5c5
< 	"github.com/chuckpreslar/inflect/types"
---
> 	"github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/briantigerchow/inflect/types"
diff -r ../../briantigerchow/inflect/languages.go Godeps/_workspace/src/github.com/briantigerchow/inflect/languages.go
5,6c5,6
< 	"github.com/chuckpreslar/inflect/languages"
< 	"github.com/chuckpreslar/inflect/types"
---
> 	"github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/briantigerchow/inflect/languages"
> 	"github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/briantigerchow/inflect/types"
```

**Comment by jbenet** [comment]
I think inflect has changed at this point, and multiaddr was fine. I think the PR is not needed anymore? thanks though @chriscool 

> It would be nice to have an automatic test that does "cd test/dependencies && make" to avoid these problems.

Yes!! it really would be nice. And (as you had mentioned) one that perhaps godep restores so people cannot godep vendor without pushing to the world (does not guarantee that the code will remain there, but at least it will handle 80% of failures).

**Comment by jbenet** [comment]
pls reopen if i'm mistaken in thinking this is no longer necessary.

**Comment by chriscool** [comment]
You are right, it is not necessary any more.

**Pull request closed without merging**
