### PR TITLE
Bump webui version

### PR DESCRIPTION
**Pull request by davidhampgonsalves**

### CODE REVIEW

**Comment by davidhampgonsalves** [comment]
The current version of webui still needs to be pinned I think QmRjkUt5A3UHjTm5uG9yZG1bRxCv4cveviQHeVTzkpXTFt

**Comment by travisperson** [comment]
I think you're missing a /ipfs/ at the front.

**Comment by davidhampgonsalves** [comment]
sorry about that

**Comment by jbenet** [comment]
@davidhampgonsalves sorry for the delay, and thank you for the PR-- still need to publish the next version

**Comment by jbenet** [comment]
Republished over at #847 -- thanks again @davidhampgonsalves and @travisperson

**Pull request closed without merging**
