### PR TITLE
benchmark CLI `ipfs add`

### PR DESCRIPTION
**Pull request by briantigerchow**
RFCR @jbenet @whyrusleeping 

offline...

```
10 MB               1       1505748119 ns/op           6.96 MB/s <-- auto updater :(
20 MB               2       1669360071 ns/op          12.56 MB/s
40 MB               1       2470719258 ns/op          16.98 MB/s
80 MB               1       1582573228 ns/op          53.01 MB/s
160 MB              1       3055764503 ns/op          54.90 MB/s <--lgtm
320 MB              1       11282053501 ns/op         29.74 MB/s
640 MB              1       20792035181 ns/op         32.28 MB/s
1 GB                1       63325554093 ns/op         21.19 MB/s
2 GB                1       136473098308 ns/op        19.67 MB/s <-- scaling issue :(
```

online is a TODO

### CODE REVIEW

**Comment by jbenet** [comment]
:+1: LGTM

**Comment by whyrusleeping** [comment]
I like this bench, addressing the perf is on my TODO list, so this will be quite helpful!

**Comment by briantigerchow** [comment]
It has several 9's of reliability when run in the default offline mode. 

I took a stab at online mode but I found coordinating activity with the background ed daemon to be quite challenging (as a first time user of the exec library). I spent a about an hour on it and decided to avoid burning too much more time on a nice-to-have.

**Comment by whyrusleeping** [comment]
does the autoupdater run *every* time? i havent noticed it ever do anything...

**Comment by briantigerchow** [comment]
The benchmark initializes a new repo before every run (stops the timer during this operation). Update will occur the first time around on newly initialized repos.

**Comment by jbenet** [comment]
we should really decide if this update stuff should ship or not. pros? cons?

**Comment by briantigerchow** [comment]
I would want to see it in the hands of a few new users. It may be helpful for them. For it to work, deploying and version must become a part of the dev workflow.

**Pull request merged**
