### PR TITLE
sharness fixes - gateway and more

### PR DESCRIPTION
**Pull request by jbenet**
- [x] common hashes file: `lib/test-lib-hashes.sh`
- [x] better init daemon that checks for both API and Gateway
- [x] core: move stdout print to daemon cmd (breaks test)
- [x] Gateway config (readonly and writable)
- [x] note in `t0110-gateway.sh` re ports
- [x] move `t0100-gateway-http.sh -> t0110-gateway-writable.sh`
- [x] make sure we use a portable tcp port check (`ss` not everywhere)
- [x] make sure all variable output is properly escaped. (always `cmd "$VAR"`. never `'cmd $VAR'`)
- [x] show sharness test options in verbose output
- [x] dont use `$path` (sometimes conflicts with some user define paths)
- [x] make sure `t0111-gateway-writable.sh` passes.

cc:
- @mildred check out changes for portable checks + a failure I get.
- @chriscool lmk if i'm doing anything wrong here

### CODE REVIEW

**Comment by jbenet** [comment]
@mappum does jenkins nor have `curl`? do we need to install it? Or, does wget have a portable way to output to stdout?

**Comment by whyrusleeping** [comment]
LGTM, covers a nice amount of test cases

**Comment by mappum** [comment]
>@mappum does jenkins nor have `curl`? do we need to install it?

Correct. Installing it is the best bet since wget doesn't support a lot of the stuff we need (e.g. `PUT` and `DELETE` requests).

**Comment by jbenet** [comment]
doesnt rebase well so im going to squash everything

**Comment by jbenet** [comment]
Installing curl portably might be messy. maybe we should use a go tool like https://github.com/dgryski/gttp downside is maybe it wont have a nice curl feature...

**Comment by jbenet** [comment]
I want to move to doing all our installations from ipfs. that would be really nice.

**Comment by jbenet** [comment]
It also wastes resources (particularly testing time) to install every time. I'll install curl in jenkins for now and we can find a good way to install it if its not available later on.

**Comment by jbenet** [comment]
Ok... curl is installed. but somehow jenkins proc cant find it.

**Comment by briantigerchow** [comment]
Is curl installed on the "bare-metal" vm? (Jenkins runs in a docker container)

**Comment by chriscool** [comment]
I wonder why my comments don't appear near the lines that I clicked on?

**Comment by chriscool** [comment]
PR #718 (test/sharness: improve t0111 using test_cmp) replaces "diff -u" with "test_cmp".

**Pull request merged**
