### PR TITLE
Spring clean

### PR DESCRIPTION
**Pull request by cryptix**
I updated two of our dependencies (fsnotify, go-uuid) and made sure that go-humanize isn't removed on 'make vendor'. It is need by the sharness test to build the `go-random/random` utility. I added the `sadhack` package under `util` to get there.

Apart from that I made four small tweaks.

* use `go build -i` in `make build` - speeds up following `go tests` drastically
* remove the unused `POut()` from pkg `util`
* removed the direct use of `go-logging` in `unixfs/io/dagmodifier_test.go` in preparation of of replacing `go-logging` with `logrus`
* renamed the old imports of `maybebtc` to brian's new account name

left overs:

* [x] fix the broken import of `github.com/briantigerchow/inflect` (@briantigerchow pushed the missing commits)
* [x] move old `go.crypto/` imports to `golang.org/x/crypto`, needs to go through `github.com/jbenet/go-multihash` as well.
* [x] move back to upstream logrus
* [x] move back to upstream inflect

### CODE REVIEW

**Comment by jbenet** [comment]
Great! LGTM.

**Comment by jbenet** [comment]
@cryptix does this race happen often now? did it get introduced? https://build.protocol-dev.com/job/race/17356/console

**Comment by cryptix** [comment]
Oh, Right.. I the tab where I wanted to create the separate issue somehow disappeared. Thank's for spotting that.

**Comment by whyrusleeping** [comment]
Ive never seen that race before. It might not be new, but I think the tests should be run a few more times. (Ill file an issue for the race). If it doesnt show up in the next 5 or so runs, I say youre good.

**Comment by briantigerchow** [comment]
thank you @cryptix

**Comment by whyrusleeping** [comment]
I want to get a chance to read this over before merging. If i forget, pester me.

**Comment by cryptix** [comment]
@whyrusleeping PTAL :wink:

**Comment by whyrusleeping** [comment]
LGTM, kinda weird that theres no jenkins test... but its probably okay

**Comment by cryptix** [comment]
Yeah.. looks like I [borked it](https://build.protocol-dev.com/job/all-the-tests/1569/). Ever since that one I didn't see runs on the other PRs I worked on.

**Comment by whyrusleeping** [comment]
@cryptix ya blew it

**Comment by jbenet** [comment]
Awesome, thanks @cryptix! super helpful

**Pull request merged**
