### PR TITLE
Add ipfs-test-lib.sh

### PR DESCRIPTION
**Pull request by chriscool**
This implements what I suggested in PR #493 (sharness: verbose output).

### CODE REVIEW

**Comment by chriscool** [comment]
A go test failed a Travis build. I doubt it is related to the change I made.

**Comment by jbenet** [comment]
@chriscool excellent! can you can rebase on master? sorry for delay -- i think a couple fsh calls may have been added since, but not sure.

**Comment by chriscool** [comment]
@jbenet I rebased and force pushed the new branch to both jbenet/go-ipfs and chriscool/go-ipfs because the PR could be updated only by pushing to chriscool/go-ipfs.

**Comment by chriscool** [comment]
Both failed tests are go tests.

**Comment by jbenet** [comment]
> Both failed tests are go tests.

Sorry. I really need to get these tests to stop failing on us. Other things are higher on my PQ atm, but will get to this soon.

**Pull request merged**
